# Taps
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/bundle'

# Binaries
brew 'bat'
brew 'bitwarden-cli'
brew 'coreutils'
brew 'croc'
brew 'findutils'
brew 'gh'
brew 'ghostscript'
brew 'git'
brew 'git-lfs'
brew 'gnupg'
brew 'gnu-sed'
brew 'graphviz'
brew 'grep'
brew 'mackup'
brew 'mas'
brew 'mongosh'
brew 'neofetch'
brew 'openssh'
brew 'pinentry-mac'
brew 'r'
brew 'screen'
brew 'starship'
brew 'terminal-notifier'
brew 'yt-dlp'

# Development
brew 'openjdk'
brew 'openjdk@11'
brew 'perl'

# Apps
cask 'adobe-acrobat-pro'
cask 'aerial'
cask 'alacritty'
cask 'alt-tab'
cask 'appcleaner'
cask 'bitwarden'
cask 'cleanshot'
cask 'devutils'
cask 'discord'
cask 'dozer'
cask 'fantastical'
cask 'iina'
cask 'imageoptim'
cask 'intellij-idea'
cask 'keka'
cask 'kekaexternalhelper'
cask 'mactex-no-gui'
cask 'microsoft-edge'
cask 'microsoft-excel'
cask 'microsoft-word'
cask 'miniconda'
cask 'mission-control-plus'
cask 'mongodb-compass'
cask 'mos'
cask 'notion'
cask 'onedrive'
cask 'rapidapi'
cask 'raycast'
cask 'readdle-spark'
cask 'sidenotes'
cask 'slack'
cask 'stats'
cask 'swish'
cask 'telegram-desktop'
cask 'tor-browser'
cask 'transmit'
cask 'transocks'
cask 'typora'
cask 'bigwig-club/brew/upic'
cask 'utm'
cask 'via'
cask 'visual-studio-code'
cask 'wechat'
cask 'sunnyyoung/repo/wechattweak-cli'
cask 'yesplaymusic'
cask 'zoom'

# Fonts
cask 'font-caskaydia-cove-nerd-font'
cask 'font-fira-code'

# Mac App Store
#! Requires apple ID: letu57@qq.com
mas 'Irvue', id: 1039633667
mas 'Pixelmator Pro', id: 1289583905
